mysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "omnisolutesting"
  dbname: "metabloxStaking"
foundationmysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "omnisolutesting"
  dbname: "foundationService"