log:
  name:  "log/log/staking.log"
  level:  "debug"
  count:  180
  rotateTime:  86400
  stdout:  true
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "omnisolutesting"
  dbname: "foundationService"
metablox:
  rpcUrl: "https://api.s0.ps.hmny.io/"
  tokenAddress: "0x7d9A974db87320Dd92fE74D31e2c4c32b3c4CB0C"
  walletPrivateKey: "01F903CE0C960FF3A9E68E80FF5FFC344358D80CE1C221C3F9711AF07F83A3BD"
  registryContract: "0x8a9DE3908DDD37b1F2D46D875214237C0505BF94"